[package]
name = "radix-engine-interface"
version = "0.11.0"
edition = "2021"

[dependencies]
sbor = { path = "../sbor", default-features = false }
radix-engine-derive = { path = "../radix-engine-derive", default-features = false }
radix-engine-common = { path = "../radix-engine-common", default-features = false }
scrypto-schema = { path = "../scrypto-schema", default-features = false }
utils = { path = "../utils", default-features = false }

hex = { version = "0.4.3", default-features = false }
strum = { version = "0.24", default-features = false, features = ["derive"] }
bitflags = { version = "1.3" }
serde_json = { version = "1.0", default-features = false }
lazy_static = "1.4.0"
const-sha1 = { git = "https://github.com/radixdlt/const-sha1", default-features = false } # Chosen because of its small size and 0 transitive dependencies
arbitrary = { version = "1.3.0", features = ["derive"], optional = true }
paste = { version = "1.0.13" }

[features]
# You should enable either `std` or `alloc`
default = ["std"]
std = ["hex/std", "serde_json/std", "sbor/std", "scrypto-schema/std", "radix-engine-derive/std", "radix-engine-common/std", "strum/std", "utils/std"]
alloc = ["hex/alloc", "serde_json/alloc", "sbor/alloc", "scrypto-schema/alloc", "radix-engine-derive/alloc", "radix-engine-common/alloc", "utils/alloc"]

# Turn on this feature to enable tracing.
trace = ["radix-engine-derive/trace"]

# This flag is set by fuzz-tests framework and it is used to disable/enable some optional features
# to let fuzzing work
radix_engine_fuzzing = ["arbitrary"]

# Ref: https://bheisler.github.io/criterion.rs/book/faq.html#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options
[lib]
bench = false
